### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by thomasp85** [huizezhang-sherry/cubble#12]
Hi

I'm in the process of updating ggforce on CRAN and my reverse dependency checks shows an issue with the CRAN version of cubble (it doesn't suggest concaveman). This seems to be fixed already on GitHub so this is mostly an inquiry on when you plan to release the next version of cubble to CRAN?

with best wishes
Thomas

**Comment by huizezhang-sherry** [comment]
Hi Thomas,

There is a release plan on cubble by the end of this week.

Regards,
Sherry

**Comment by huizezhang-sherry** [comment]
Update: still waiting for the latest release of dplyr
