### ISSUE TITLE
Recommend keep magrittr pipe

### ISSUE THREAD

**Issue by emitanaka** [huizezhang-sherry/cubble#4]
I'd recommend keeping the magrittr pipe %>% (it's part of tibble anyway so won't make difference). The native pipe is only available for R version >=4.1.0 which was only released last year. There are going to be a number of people who won't be able to use it so it's just adding a barrier for people to use your package.

**Comment by huizezhang-sherry** [comment]
add back in commit 519867771574f3db0f8b14e6c85d7b88f5338188
